### ISSUE TITLE
Can't read /data/addons/git/774437fd/octoprint/FS/octoprint/config.yaml: Invalid Add-on config!

### ISSUE THREAD

**Issue by PrathikGopal** [fredrikbaberg/hassio-addons#123] opened 2021-03-25 03:50 UTC
**I see the below errors on the supervisor logs, the addon seems to run fine though.**

> 21-03-25 01:26:59 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/774437fd/octoprint/FS/octoprint/config.yaml: Invalid Add-on config!. Got ordereddict([('accessControl', ordereddict([('autologinAs', 'homeassistant'), ('autologinLocal', True), ('localNetworks', ['172.30.32.2'])])), ('folder', ordereddict([('data', '/data/octoprint/data'), ('generated', '/data/octoprint/generated'), ('logs', '/data/octoprint/logs'), ('plugins', '/data/octoprint/plugins'), ('virtualSd', '/data/octoprint/virtualSd'), ('timelapse_tmp', '/data/octoprint/timelapse/tmp'), ('printerProfiles', '/config/octoprint/printerProfiles'), ('slicingProfiles', '/co...
> 21-03-25 01:26:59 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/774437fd/octoprint_dev/FS/octoprint/config.yaml: Invalid Add-on config!. Got ordereddict([('accessControl', ordereddict([('autologinAs', 'homeassistant'), ('autologinLocal', True), ('localNetworks', ['172.30.32.2'])])), ('folder', ordereddict([('data', '/data/octoprint/data'), ('generated', '/data/octoprint/generated'), ('logs', '/data/octoprint/logs'), ('plugins', '/data/octoprint/plugins'), ('virtualSd', '/data/octoprint/virtualSd'), ('timelapse_tmp', '/data/octoprint/timelapse/tmp'), ('printerProfiles', '/config/octoprint/printerProfiles'), ('slicingProfiles', '/co...
> 21-03-25 01:26:59 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/774437fd/octoprint/FS/octoprint/config.yaml: Invalid Add-on config!. Got ordereddict([('accessControl', ordereddict([('autologinAs', 'homeassistant'), ('autologinLocal', True), ('localNetworks', ['172.30.32.2'])])), ('folder', ordereddict([('data', '/data/octoprint/data'), ('generated', '/data/octoprint/generated'), ('logs', '/data/octoprint/logs'), ('plugins', '/data/octoprint/plugins'), ('virtualSd', '/data/octoprint/virtualSd'), ('timelapse_tmp', '/data/octoprint/timelapse/tmp'), ('printerProfiles', '/config/octoprint/printerProfiles'), ('slicingProfiles', '/co...
> 21-03-25 01:26:59 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/774437fd/octoprint_dev/FS/octoprint/config.yaml: Invalid Add-on config!. Got ordereddict([('accessControl', ordereddict([('autologinAs', 'homeassistant'), ('autologinLocal', True), ('localNetworks', ['172.30.32.2'])])), ('folder', ordereddict([('data', '/data/octoprint/data'), ('generated', '/data/octoprint/generated'), ('logs', '/data/octoprint/logs'), ('plugins', '/data/octoprint/plugins'), ('virtualSd', '/data/octoprint/virtualSd'), ('timelapse_tmp', '/data/octoprint/timelapse/tmp'), ('printerProfiles', '/config/octoprint/printerProfiles'), ('slicingProfiles', '/co...

**Comment by fredrikbaberg** [comment] 2021-03-26 08:36
Thank you for reporting this.
I'm not sure why that happens, but I've observed it on my Home Assistant install. It looks like the supervisor tries to interpret the Octoprint configuration as add-on config, which will fail.

I'll wait with investigating this, as it does not break right now, and see if the next update to Home Assistant solves this.

**Comment by fredrikbaberg** [comment] 2021-03-30 07:34
@PrathikGopal I'm not sure if you've seen the issue I created in supervisor, but I've reported this as a bug. It seems to be confirmed but is low priority.
I can work around the issue through renaming some files, and will probably do so the next time I update the add-ons, but am not sure when that will be.

**Comment by PrathikGopal** [comment] 2021-03-31 02:25
Thank you for creating this add on and looking into the issue. I’m ok, as long as it will be fixed.

**Comment by fredrikbaberg** [comment] 2021-04-01 07:34
This was not fixed by #127, I'll make another attempt.
Note that fixing this will not require anyone to update the addon, it's just modification of filenames for when the addon is build.

**Closed** 2021-04-01 07:45 UTC
