### ISSUE TITLE
RTC support

### ISSUE THREAD

**Issue by alexyao2015** [fredrikbaberg/hassio-addons#264] opened 2022-01-13 04:40 UTC
Instead of mjpgstreamer, can you see if aiortc would work/is faster? 

Octoprint [recently added support for webrtc](https://github.com/OctoPrint/OctoPrint/pull/4225). See [a guide](https://community.octoprint.org/t/low-latency-h264-streaming-support-w-webrtc/36996), and the [aiortc example](https://github.com/aiortc/aiortc/blob/d5d1d1f66c4c583a3d8ebf34f02d76bc77a6d137/examples/webcam/webcam.py).

**Comment by fredrikbaberg** [comment] 2022-01-13 21:31
I assume this is the same as #236? If so, I did an attempt when that was created but did not manage to get it to run. Not sure what the exact issue was, but I suspect it was related to compiling för Alpine Linux.

I'm currently out of time to investigate it further. Hopefully I'll have time in a month or two.

**Comment by alexyao2015** [comment] 2022-01-14 04:22
Its similar, but this is using aiortc. Not sure if it is better or not than https://github.com/mpromonet/webrtc-streamer that you mentioned over there. 

As a side, any reason why you decided to make this all one container instead of using the internal dns for communication between containers? Just for simplicity? I'm interested in running all 3 of the printing UI's (octoprint, fluidd, and mainsail) because they all seem to offer different unique benefits, but it wouldn't make sense to integrate them all into one container if someone didn't want one piece or another. 

Additionally, I've noticed you can update klipper/moonraker from octoprint, but I think it would be nifty if those were built into separate images and individually published. This would allow the user to use home assistant for backups and rollbacks of the instance if something were to go wrong. I can look into automating this if its something you wouldn't have time for.

**Comment by fredrikbaberg** [comment] 2022-01-16 03:29
I made it a single container for convenience with a single addon, simplicity in testing and updates, and image size. Since I moved to Klipper it allowed me to use the same addon. While the image contains all features, they are compressed and will only be extracted the first time they are enabled. As for image size, OctoPrint plugins may require build tools, and there is an overlap with Klipper. Finally, the 3DPrinter addon should allow for backups from Home Assistant.

I agree that it could be nice to divide the components into different addons/containers, assuming we find a partition that works. OctoPrint, camera and Klipper UI would make sense. The issue I see is the communication between OctoPrint and Klipper. Fluidd and Mainsail requires Moonraker, but OctoKlipper uses another method (running both at the same time causes issues in the current addon).

- OctoPrint itself is straightforward, the issue is communication between OctoKlipper and Klipper.
- For camera there is already _mjpg-streamer_ as a separate addon. A separate aiortc or webrtc-streamer would be a good start.
- Klipper + Moonraker should be straightforward to separate. I'm not sure if user configuration is needed though.
- For Klipper UI I've attempted to add Fluidd and Mainsail before, with an option to switch between OctoPrint/Fluidd/Mainsail but had issues I believe were related to proxy configuration.

**Comment by fredrikbaberg** [comment] 2023-01-13 20:04
I'll close this as I haven't been able to complete the work on it.

If there are ideas how to add RTC I'm happy to accept PRs to the following repo: https://github.com/fredrikbaberg/ha-3dprinter-addons. There I'm also trying to divide the functions into different add-ons, as suggested (though the main difficulty will be when multiple add-ons need access to the same files, as described above, since I didn't want to use /share).

**Closed by fredrikbaberg** 2023-01-13 20:04 UTC
