### ISSUE TITLE
Problem with the webcam

### ISSUE THREAD

**Issue by paolocontee** [fredrikbaberg/hassio-addons#113] opened 2021-01-09 17:56 UTC
Thanks for add on of octoprint in HA!

I have a problem on how to connect the usb webcam, could you explain me all the steps to be able to view it. Especially the code to add in the HA config.yaml

Thanks!

**Comment by fredrikbaberg** [comment] 2021-01-21 22:12
Unfortunately I don't have access to a USB webcam for testing.
There is a reply in the community forum, could that help? https://community.home-assistant.io/t/repository-octoprint/22883/106

In the configuration for the addon there are some parameters for the camera, I'm not sure if those need to change. I think the default should be OK.
The other thing is to start mjpg-streamer, which is done from the power menu in OctoPrint WebUI.

**Comment by fredrikbaberg** [comment] 2021-01-22 00:03
I now noticed you wrote HA config.yaml. This is not something I've tested. I hope the link above is relevant.

My guess is that you would have to:
- Make the camera work in OctoPrint.
- Set port so you can access the camera by IP/hostname (perhaps it is possible to make it work through Ingress, but I've never tried that).
- Add the camera in Home Assistant. I would assume this integration would work: https://www.home-assistant.io/integrations/mjpeg/

**Comment by fredrikbaberg** [comment] 2021-01-28 14:24
I can confirm that the mjpg integration works, as I've just tested it.

Have you been able to get the camera to work?

**Comment by Aaronhrndz** [comment] 2021-02-07 22:45
Hi, how can I connect a raspberry native camera stream to octoprint addon that actually works on Home Assistant OS with startx.elf and fixupx.dat patches? In Home Assistans the camera is working via rpi_camera integration but I cannot parse it to a mpeg stream to use it on Octoprint

**Comment by fredrikbaberg** [comment] 2021-02-08 13:01
> Hi, how can I connect a raspberry native camera stream to octoprint addon that actually works on Home Assistant OS with startx.elf and fixupx.dat patches? In Home Assistant the camera is working via rpi_camera integration but I cannot parse it to a mpeg stream to use it on Octoprint

I've been unable to make the rpi_camera integration work with Home Assistant installed according to https://www.home-assistant.io/getting-started/. Instead, I did the "trick" with start_x.elf and fixup_x.dat (https://raspberrypi.stackexchange.com/a/51440), no rpi_camera configuration used.

**Comment by Aaronhrndz** [comment] 2021-02-08 13:22
> > Hi, how can I connect a raspberry native camera stream to octoprint addon that actually works on Home Assistant OS with startx.elf and fixupx.dat patches? In Home Assistant the camera is working via rpi_camera integration but I cannot parse it to a mpeg stream to use it on Octoprint
> 
> I've been unable to make the rpi_camera integration work with Home Assistant installed according to https://www.home-assistant.io/getting-started/. Instead, I did the "trick" with start_x.elf and fixup_x.dat (https://raspberrypi.stackexchange.com/a/51440), no rpi_camera configuration used.

I've get it working too with this method on Home Assistant side, but I don't know how to use it on Octoprint Addon. I can use it via rpi_camera as the official Home Assistant says (loading the startx alternative firmware from your link) but can't figure out how to integrate it in the Octoprint addon

**Comment by Aaronhrndz** [comment] 2021-02-08 13:33
> I can confirm that the mjpg integration works, as I've just tested it.
> 
> Have you been able to get the camera to work?

Yes but only on Home Assistant side, following a mix between official home assistant rpi_camera guide, your link and this: https://gist.github.com/enegaard/a57af286205914bd912270c89650fb1b

Mine are a raspberry 4 so the alternative firmware files are others, also no v4l utils is needed or mounting docker since I have direct access to boot partition from sdcard and I can set directly alternative files to boot. 

Can you copy me the camera fragment on configuration.yaml (from home assistant) with the mpeg config and the config.yaml (from octoprint addon config) for get it working? I've tried almost everything but no results :(

Thank you so much!

**Comment by fredrikbaberg** [comment] 2021-02-08 18:24
> > I can confirm that the mjpg integration works, as I've just tested it.
> > Have you been able to get the camera to work?
> 
> Yes but only on Home Assistant side, following a mix between official home assistant rpi_camera guide, your link and this: https://gist.github.com/enegaard/a57af286205914bd912270c89650fb1b
> 
> Mine are a raspberry 4 so the alternative firmware files are others, also no v4l utils is needed or mounting docker since I have direct access to boot partition from sdcard and I can set directly alternative files to boot.
> 
> Can you copy me the camera fragment on configuration.yaml (from home assistant) with the mpeg config and the config.yaml (from octoprint addon config) for get it working? I've tried almost everything but no results :(
> 

As I wrote before, I have nothing related to rpi_camera in my Home Assistant configuration.yaml. I believe this issue was originally about the reverse, make the camera in OctoPrint available in Home Assistant, which I do with the following configuration:
```
# configuration.yaml
camera octoprint:
  - name: OctoPrint
    platform: mjpeg
    mjpeg_url: http://<URL>:8000/?action=stream
    still_image_url: http://<URL>:8000/?action=snapshot
```
I've also tried to enable rpi_camera in my config, which seems to prevent mjpg-streamer from launching in the OctoPrint addon. So, you should choose between rpi_camera in Home Assistant or mjpg-streamer in the addon.

For the addon I use the default, currently:
```
# OctoPrint addon configuration
mjpg_input: input_uvc.so -n
mjpg_output: output_http.so -w /www_mjpg
request_rescue: false
add_build_packages: false

```

> My goal is achieve camera streaming on octoprint with an official raspberry camera connected via ribbon cable to home assistant machine (HassOS on the rpi4) running the octoprint addon
> 
> Thank you so much!

Just to confirm, did you start mjpg-streamer from the OctoPrint addon? Without the rpi_camera configuration in Home Assistant?

**Comment by Aaronhrndz** [comment] 2021-02-08 19:44
Oh, nice point, I was trying to enable it by the opposite way. It works! I'm gonna try this with the new hassOS release over 5.11 version and the new alternative startx firmware
Thank you!

**Comment by fredrikbaberg** [comment] 2021-03-30 07:38
I'm closing this issue now. There should be documentation available on how to enable the camera and the workaround that may be required after HassOS updates.

**Closed by fredrikbaberg** 2021-03-30 07:38 UTC
