### ISSUE TITLE
stl files not being downloaded

### ISSUE THREAD

**Issue by bruvv** [fredrikbaberg/hassio-addons#176] opened 2021-09-30 20:48 UTC
I'm crosslinking this because I'm using this add-on with this plugin: https://github.com/appdevelopmentandsuch/Thingiverse-Downloader/issues/14 and for some reason the debug log is empty and I cannot get it to accept stl files. 
It looks like it needs either cura engine or the slic3r engine. Can this be added to the docker ?

For example: https://github.com/kennethjiang/octoprint-docker-with-slicers or: https://github.com/rludwiczak/octoprint-docker-pi

**Comment by fredrikbaberg** [comment] 2021-09-30 21:44
I need some more information for this.
- What version of the addon are you using?
- Could you clarify what the issue is?
  - Which debug log is empty?
  - What is it that does not accept stl files?
- Do you suspect a bug in the addon, or is it a feature request to include a slicer?

It seems the Thingiverse-Downloader plugin requires a plugin that can show stl files, did you try to install STL Viewer which is one of the suggested plugins?

**Comment by bruvv** [comment] 2021-09-30 21:51
I'm using the latest version of the next add-on. 
You can specify special log files within octoprint, so I enabled debug log for thingiverse downloader but nothing appears
Octoprint doesn't accept stl files. 

When diving more into it. It's a feature request to add slider binanries either from slic3r or cura. 

The thingiverse downloader needs a slicer (the stl viewer does so too). There are 2 options:
- slic3r
- cura

Either one has to be embedded into the docker. (see examples in post #1

**Comment by fredrikbaberg** [comment] 2021-09-30 23:16
STL Viewer should not need a slicer (as it just views STL files), I've just tried it on a clean install of OctoPrint-Next with a stl I uploaded manually. However, the Thingiverse Downloader plugin seems to have limited use without a slicer, as you can't really print a raw stl file directly.

I can confirm that I've also encountered the following issues:
- There is no log output from the plugin, even after setting the log level to debug.
- Downloaded files do not appear under files.

I'm not sure those are issues caused by this addon, more testing is required, preferably on a clean OctoPi install. I'll see if I have time this weekend.

There are currently some other things I want to fix with the addon, but am unable to right now. I'm not sure adding a slicer to the addon is a good idea, but will take it under consideration.

**Comment by fredrikbaberg** [comment] 2021-10-02 23:11
I tried to build a minimal version locally, with only OctoPrint, and did not encounter the issue with STL files not being downloaded. I'll have to see if it occurs as I add the other required components.

I've also done some initial attempts to add either Slic3r or SuperSlicer to the addon. It is not really straightforward as the addon is based on Alpine Linux but most instructions are for Debian/Ubuntu/Raspbian.

**Comment by bruvv** [comment] 2021-10-03 07:24
Thanks for the update

**Comment by bruvv** [comment] 2021-10-05 14:24
Also found another issue but that might be related to hassOS: https://github.com/jneilliii/OctoPrint-MyMiniFactory/issues/15

**Comment by fredrikbaberg** [comment] 2021-10-05 21:43
I'll have to look at the MyMiniFactory part later as it's (probably) a separate issue. Initial guess is it's related to proxy configuration inside the addon, I've had issues with that before.

I think I've found a solution to the issue with Thingiverse Downloader - the file is downloaded, but not to the correct location, that's why it does not appear. However, I can't push the fix to OctoPrint Next without breaking the addon for some reason.

Regarding slicer, it's straightforward to add CuraEngine Legacy (15.04.6), but that is from 2016. Latest release of Slic3r seems to be from 2018, but there are derivatives such as Prusa-Slicer and SuperSlicer with more recent updates. Adding one of those requires me to change base image from Alpine (default for addons in Home Assistant) to Debian or Ubuntu.

I've started with a version based on Debian, I'll see if I can get the core parts up and running this week. SuperSlicer may have to wait as it takes almost 70 minutes to build on my laptop (Core i3 CPU, NVMe SSD and 16 GB RAM) - my main Home Assistant instance even ran out of storage before the build completed.

**Comment by fredrikbaberg** [comment] 2021-10-19 16:45
After looking at the image size I can't really motivate the change from Alpine to Debian as base image. For amd64 architecture that change alone seems to increase the image size from 900MB to 1500MB, before installing Slic3r.

I'll most likely go back to Alpine as base, but will keep CuraEngine Legacy available. If there is a way to build Slic3r or similar for Alpine I'm happy to add that, but I haven't succeeded.

I saw a web-based slicer among the plugins, https://plugins.octoprint.org/plugins/gridspace/. I haven't tested it, but it could perhaps be an option?

**Comment by fredrikbaberg** [comment] 2021-11-03 15:30
I'm closing this as the following should be fixed:
- Files properly downloaded from Thingiverse Downloader
- Added CuraEngine Legacy

The changes are added to the addon "3DPrinter", which is intended to replace all the "OctoPrint" variations in this repository by the end of 2021.

**Closed by fredrikbaberg** 2021-11-03 15:30 UTC
Labels: enhancement
